plugin:
  name: "WooCommerce Carousel/Grid Marketplace & Pricing"
  slug: "wc-carousel-grid-marketplace-and-pricing"
  prefix: "WC_CGMP"

git:
  remote_url: "https://github.com/Jerel-R-Yoshida/wc-carousel-grid-marketplace-and-pricing"
  branch_dev: "develop"
  branch_main: "master"

versioning:
  current: "1.1.6"

testing:
  phpunit: false
  phpunit_config: ""
